-- Routine Notifications Table
-- 알림 설정을 저장하는 테이블
create table if not exists routine_notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  routine_id text not null, -- 클라이언트 상의 routine ID (또는 goal ID)
  notify_time time not null, -- 알림 시간 (HH:MM:SS)
  active boolean default true,
  days_of_week text[], -- 예: ['Mon', 'Tue'] (Optional)
  created_at timestamptz default now()
);

-- 인덱스: 유저별 조회 성능 최적화
create index if not exists idx_routine_noti_user on routine_notifications(user_id);


-- Routine Logs Table
-- 루틴 성공/실패 이력을 누적하여 분석하기 위한 로그 테이블
create table if not exists routine_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  routine_id text not null,
  category text, -- 'health', 'study', 'mind' 등 분석용 태그
  is_success boolean default true,
  completed_at timestamptz default now(), -- 완료 시점
  duration_seconds integer, -- 소요 시간 (Optional)
  metadata jsonb -- 추가 정보 (기분, 메모 등)
);

-- 인덱스: 날짜별/유저별 분석용
create index if not exists idx_routine_logs_user_date on routine_logs(user_id, completed_at);

-- RLS (Row Level Security) 정책 설정
alter table routine_notifications enable row level security;
alter table routine_logs enable row level security;

create policy "Users can view own notifications"
  on routine_notifications for select
  using (auth.uid() = user_id);

create policy "Users can insert own notifications"
  on routine_notifications for insert
  with check (auth.uid() = user_id);

create policy "Users can update own notifications"
  on routine_notifications for update
  using (auth.uid() = user_id);

create policy "Users can delete own notifications"
  on routine_notifications for delete
  using (auth.uid() = user_id);

create policy "Users can view own logs"
  on routine_logs for select
  using (auth.uid() = user_id);

create policy "Users can insert own logs"
  on routine_logs for insert
  with check (auth.uid() = user_id);
